### ISSUE TITLE
Changes to the sample students file

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#123]
The sample students file template

![image](https://user-images.githubusercontent.com/1979690/79780980-62dc4f00-8302-11ea-9909-6bc837336680.png)

and the contents looks like

![image](https://user-images.githubusercontent.com/1979690/79781182-b5b60680-8302-11ea-8b40-39e0f4ffeda4.png)

Let's make the following improvements to make this an easier template to understand:

- [ ] change the file name from class_list_CS_3990_5969_20191__1____moreGroups.xlsx to sample_student_roster_file.xlsx
- [ ] change the columns to only include the required ones. I think that means removing Session, UID, Hawkid?
- [ ] change the emails from @uiowa.edu to @example.com
- [ ] There should be more than 1 student/group - otherwise the instructor may be confused why each student has their own group. Change the groups/metagroups so that there are 3-4 students per group and two metagroups

**Comment by sah0017** [comment]
All of these items have been addressed in the sample file.
