### ISSUE TITLE
Refactoring spreadsheet usage

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#135]
The server's persistent data is currently spread across spreadsheets and sql database. Some of the tables stored as spreadsheets are involved in frequent transactions, particularly the evaluations table. Ideally, we would migrate most tables to sql database so that all transactions be over the sql database, leaving the spreadsheets as read-only use.

**Comment by sah0017** [comment]
Closing this because this activity is in progress and is covered by other issues.
