### ISSUE TITLE
Remove hardcoded TW.json filename

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#141]
Multiple places in app.py separately hardcode "TW.json" as the filename storing the rubric configuration for a project. This issue calls for two changes:

1) this file should be named more usefully as: "rubric_config.json"

Note before merging to production: any existing servers need to rename all instances of TW.json to rubric_config.json

2) Instead of having the string literal appear in many places in the code, there should be one global variable where the literal is set

**Comment by sah0017** [comment]
JSON for rubric files now located in the database.
