### ISSUE TITLE
Test legacy users after username=>email change

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#148]
specific test case proposed by @zhouhuan200010pm 

1. legacy user creates user-based name
2. change to new version
3. legacy user logs in with their username (but it says email)

**Comment by bmyerz** [comment]
@zhouhuan200010pm Update label to bug if this test finds a crash

**Comment by zhouhuan200010pm** [comment]
bug found - entering the email will have the "not a user" tag

**Comment by bmyerz** [comment]
after thinking about this, let's talk about it at next meeting (July 20) before we implement any fix

**Comment by bmyerz** [comment]
At this point I think we need to deprecate older username based accounts - I don't think it will be an issue at this point, since most new accounts are in the new format.
