### ISSUE TITLE
Turning off scores investigation

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#149]
Currently can use
![image](https://user-images.githubusercontent.com/1979690/86963361-0717aa00-c12a-11ea-96b6-3704d40f98cd.png)

to turn on 
![image](https://user-images.githubusercontent.com/1979690/86963292-e6e7eb00-c129-11ea-9df2-908c26cff468.png)
and off
![image](https://user-images.githubusercontent.com/1979690/86963320-f404da00-c129-11ea-9c92-3db5e5d5ab0b.png)
the numbers on the radio buttons.

Users ask that the rating words (ie rarely, sporadically) can also get toggled by a switch.

**Comment by bmyerz** [comment]
Not clear what is really desired here. Let's postpone working on this issue until we get clarification from users.

**Comment by bmyerz** [comment]
looking back at the master list rubrics; we probably want scores on/off teacher as is or always on. For email, choose whether or not to share score

**Comment by sah0017** [comment]
Creating a new React version of this page.
