### ISSUE TITLE
Attendance improvements

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#167]
![image](https://user-images.githubusercontent.com/1979690/89471382-a046da00-d743-11ea-9075-3ca8d5487f38.png)

Attendance feature appears to work. That is, if you click checkboxes and then click "save", it will store those students names in the spreadsheet ("students" column in "eva" sheet). However, to make it much less confusing, we need the following improvements:

- [ ] make it harder to _forget_ to save. Users may easily forget
- [ ] some visual indication that clicking on save did anything, e.g., removing the save button and replacing with the word "Saved!"
- [ ] by default, if you never save the attendance of a group, then all students are counted as "here" in the spreadsheet. However, in the spreadsheet it is confusing that for groups you *did not* save attendance for, the names of students are still in there. But, there is a difference!

Here is a team where I didn't save attendance
Mosley, Korban,Meyer, Sienna,Boyce, Bradlee,Patterson, Lilly

Here is a team where I did save attendance
Morales,   Conah|Cotton, Libbie

Notice the difference is the delimiter | is used. So really, by default, groups with no attendance saved should have a blank cell in the "students" column of the spreadsheet.

**Comment by sah0017** [comment]
@ksoria0205 Make note of this in the figma design.
