### ISSUE TITLE
Deleting a Project does not delete its Evaluations (and other stuff)

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#183]
To reproduce user-visible website error.

1. Create a Project
2. Create at least one Evaluation in that Project
3. Delete the Project (using Manage Projects)
4. Create a new Project **with the same name as the old Project**

You will now see inconsistencies. For example, the old Evaluation is still listed in some places and not in others.

To fix this problem, make sure that when a row is deleted from Project table of database that all rows with that (project_name, project_owner). For example, in these tables: Evaluation, EmailSendingRecord,Permission.

**Comment by Junnan-wang** [comment]
1. Firstly, we do not have a button to delete an evaluation.
2. If we delete the whole project, then we create a project with the same name as the deleted project, all the evaluations associated with the deleted project would still exist.
3. In addition, after re-creating the project, these evaluations appeared are actually not usable. If click into the evaluations created before the deletion + re-creation, there will be an IndexError screen:
![image](https://user-images.githubusercontent.com/62077662/110569824-a8705900-811a-11eb-8a8f-cd7031e2175c.png)
