### ISSUE TITLE
Date and time - formatting and bug

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#189]
![image](https://user-images.githubusercontent.com/1979690/90192368-6e0f2b00-dd88-11ea-90af-50bc31c01536.png)
In the grading page.
Don't use the < > brackets.

**Comment by bmyerz** [comment]
There's also a bug where clicking on the next group messes up the timestamp

![image](https://user-images.githubusercontent.com/1979690/90192714-1de49880-dd89-11ea-8df8-5fcef1176a7a.png)

**Comment by zhouhuan200010pm** [comment]
Haven't Fix the issue yet, but could change it by fixing the Javacript function "updateLastEditTime()" or simply delete this feature
