### ISSUE TITLE
See all details spreadsheet right boundary is off

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#191]
![image](https://user-images.githubusercontent.com/1979690/90193790-4e2d3680-dd8b-11ea-9e2d-11b79b20009b.png)

Table starts on the left in the correct place, but right side bleeds into the black right margins

**Comment by bmyerz** [comment]
Hard to replicate this problem. But we should consider that we really just want to know "which groups haven't had ALL items rated yet". We don't care so much about each column check marked. So could be a third "yellow" list of groups in addition to green and red.

**Comment by sah0017** [comment]
Creating a new React page of this.
