### ISSUE TITLE
Cleanup the evaluations xlsx

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#192]
Remove the first sub-sheet, since it is blank and might look confusing. Also rename eva to evaluations.

![image](https://user-images.githubusercontent.com/1979690/101959540-2039f080-3bcb-11eb-9dfd-e3b98a3a4e97.png)

**Comment by bmyerz** [comment]
User feedback noted this problem, so re-prioritizing.

> The top sheet was disconcertingly blank, but the other sheets had stuff on them.

**Comment by sah0017** [comment]
I'm closing this issue since we are moving to storing evaluations in the database rather than in an Excel spreadsheet.
