### ISSUE TITLE
Evaluations scores should be numbers

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#193]
The columns for scores (i.e., name in the json rubric) are made to be text by default. But the common case is that the "names" are numeric scores. So when the evaluations spreadsheet is exported, we should detect if columns are numeric and then set them to be numeric.

See the green errors on the "numeric" cells that excel is treating as text.
![image](https://user-images.githubusercontent.com/1979690/90194213-59cd2d00-dd8c-11ea-8d53-bebac25e26e8.png)

**Comment by sah0017** [comment]
Closing this issue because we will no longer be using spreadsheets to store this data.
