### ISSUE TITLE
Make saving a rating harder to forget to do

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#207]
User feedback:

> My biggest early mistake was forgetting to hit SAVE as I completed each characteristic rating.   

This same issue was raised by another user

> One thing I did no.ce is that I had to hit "save" for every score I clicked.

We should think about how to make sure the instructor doesn't forget to save a rating. 

![image](https://user-images.githubusercontent.com/1979690/101958750-8b82c300-3bc9-11eb-865c-f42aa7a94e86.png)

User also noted similar issue with attendance feature:

> ... Also true for the attendance box.

We will track that one at #167

**Comment by sah0017** [comment]
No longer relevant
