### ISSUE TITLE
Refactor UI status messages

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#209]
terminology for this issue: "status message" is something like

![red status message at the top of the manage projects page that says: You cannot give permission to yourself](https://user-images.githubusercontent.com/1979690/109233694-e8852280-778f-11eb-9aa0-74a3414100dc.png)

The code for displaying status messages are a bit of a mess. A few problems
- the whole message is encoded into the url
- there is no indirection, so a change of the message wording could affect code elsewhere
- there is no indication of positive (green) versus negative (red) messages. In some places, we are coping with this by looking for specific message wordings. That is, message text is conflated with the type of message.

I refactored the messages for the Manage Projects page in 0d7410c0214139fa9ff3b7d776368fc405220abb. But there are still other pages with the old code. For example, the create project page.

**Comment by sah0017** [comment]
No longer relevant
