### ISSUE TITLE
Server environment for easier development of server configuration

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#214]
Certain issues require tweaking the dev/prod server configurations until we get them right. It also requires developers to have write access to the dev/prod server. Two examples issues where this is a barrier are:
- refactoring to multi file #138 requires tweaks to Apache to find our app
- getting emails working #169

Since we do not administer the server, it would be nice to have a development environment, such as a Docker image with Apache, mod_wsgi + flask, and optionally MySQL (although we could optionally run in sqlite3 mode if not making tweaks to MySQL).

**Comment by sah0017** [comment]
No longer relevant
