### ISSUE TITLE
Rating page not consistent

### ISSUE THREAD

**Issue by Junnan-wang** [Lunatic-Labs/rubricapp#216]
When creating an evaluation, the webpage of the rating screen is not consistent on the screen.
![Capture](https://user-images.githubusercontent.com/62077662/112784774-17edb000-9018-11eb-9553-c91e4e2beb1d.PNG)
As shown here, the order of the groups is random.

**Comment by Junnan-wang** [comment]
Another issue is when you are on rating page, if clicking the button at top: (like Week 1, a, etc in this case)
![image](https://user-images.githubusercontent.com/62077662/112788834-63f12280-9021-11eb-8865-f20390fd1a5d.png)
The webpage will navigate to create evaluation page:
![image](https://user-images.githubusercontent.com/62077662/112788906-85eaa500-9021-11eb-8f21-5a59ba179043.png)

**Comment by sah0017** [comment]
No longer needed - Creating a new rating page.
