### ISSUE TITLE
Improvements to /project_profile

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#218]
- [ ] Change the wording "Give permission of this project to other users / Manage the permission you have granted". Change to "Add or remove users for this project".

- [ ] Change Permission title to Sharing this project

- [ ] Change Evaluation title to Evaluations

- [ ] Change "Manage Rubrics" to "Manage Projects" breadcrumb
![image](https://user-images.githubusercontent.com/1979690/113777069-3aef2280-96f0-11eb-9e05-61004314eb2e.png)

- [ ] change this table to have just two headers: "share to" -> "Share with";  "Authority" -> "Actions"; and delete "Add" (make sure to keep the Create button though). Change the wording "Create new Permission to share your rubric" to "Share this project with another user". Also delete the ellipses (...) at the bottom 
![image](https://user-images.githubusercontent.com/1979690/113777510-ca94d100-96f0-11eb-9f92-1676382b320d.png)

- [ ] fix the /project_profile page display. Right now it seems to overflow off the right side
![image](https://user-images.githubusercontent.com/1979690/113776756-daf87c00-96ef-11eb-8bb7-6124106a651e.png)

- [ ] test Display all details and Delete to see if it actually works. If it is broken, just report it in this issue, do not fix yet.
![image](https://user-images.githubusercontent.com/1979690/113777660-0039ba00-96f1-11eb-8342-abcd83612efe.png)

![image](https://user-images.githubusercontent.com/1979690/113777653-fd3ec980-96f0-11eb-84d9-a545cd88a0ff.png)

- [ ] test update group and see if it actually works. If it is broken, just report it in this issue, do not fix yet.

![image](https://user-images.githubusercontent.com/1979690/113777742-21020f80-96f1-11eb-8e67-424b2a57896e.png)

**Comment by sah0017** [comment]
@ksoria0205 for wireframe consideration

**Comment by sah0017** [comment]
We have new screens and terminology.
