### ISSUE TITLE
Grading page has duplicate (or unused?) HTML in the ToolBox

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#222]
See for example the meta groups buttons, or studentName part in Attendance. Some of the HTML appears to be displayed and other might be inactive.

**Comment by Junnan-wang** [comment]
In the html of rating page, if search for a specific name at the attendance (Here is "Werner, Lillia"), there will be multiple occurrence of the name, even though the name appears in screen for only one time:
![image](https://user-images.githubusercontent.com/62077662/115502596-c9a88700-a23a-11eb-8055-3cb120d9fb66.png)
![image](https://user-images.githubusercontent.com/62077662/115502604-cc0ae100-a23a-11eb-9fcd-bcd57ab31594.png)

Later on, it was found out that the code for the whole left side bar is duplicated.
![image](https://user-images.githubusercontent.com/62077662/115502993-623f0700-a23b-11eb-843e-b888224366db.png)

**Comment by sah0017** [comment]
Closing because we are creating a new React version.
