### ISSUE TITLE
When share a Project permission to a user twice, crash page instead of a red Alert

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#223]

**Comment by bmyerz** [comment]
We should fix it during #209

**Comment by Junnan-wang** [comment]
This is what will happen if share the same project to another user for twice:
![image](https://user-images.githubusercontent.com/62077662/115503253-bd70f980-a23b-11eb-9d09-6a6f4713c143.png)

**Comment by sah0017** [comment]
We're doing this differently now.
