### ISSUE TITLE
Resolve comments from Selenium tests closed pull request

### ISSUE THREAD

**Issue by sah0017** [Lunatic-Labs/rubricapp#226]
I merged the pull request that added Selenium tests to the master branch.  However, the previous code owner made a number of comments about the Selenium tests in the pull request.  Someone should go back to the closed pull request and try to address the comments that were attached to the pull request.

**Comment by mekealbrown** [comment]
All comments have been commented on and resolved. Most comments were concerning formatting and/or naming convention issues that have been fixed as of the current state of the test suite. The remainder of the comments were targeted to questionable logic found in some of the test/driver files; these logical issues have been fixed as of the latest state of the test suite.
