### ISSUE TITLE
AT:  Implement the existing Selenium Tests

### ISSUE THREAD

**Issue by sah0017** [Lunatic-Labs/rubricapp#227]

**Comment by mekealbrown** [comment]
test1 is failing, looks like Selenium locators aren't correctly implemented.

**Comment by sah0017** [comment]
Is this issue ready to close?

**Comment by sah0017** [comment]
I'm going to close this because we will need to modify our Selenium tests to go with the new screens.  We can add a separate issue for each screen as we build the new screens.
