### ISSUE TITLE
AT:  create a selenium test incorporating account.html

### ISSUE THREAD

**Issue by ksoria0205** [Lunatic-Labs/rubricapp#242]
You can either create a test or add to an existing test to incorporate the file. It is part of the rubric page.

**Comment by mekealbrown** [comment]
Two tests currently written and passing. Test structure written out and further tests will be written. Looking to get full coverage tests completed by Wednesday.

**Comment by mekealbrown** [comment]
Pull request opened. Will move this to completed once changes are merged
