### ISSUE TITLE
Add instructions on how to set up and run Selenium tests to the Wiki

### ISSUE THREAD

**Issue by sah0017** [Lunatic-Labs/rubricapp#245]

**Comment by mekealbrown** [comment]
Wiki updated. If reviewed to be satisfactory, I will close this issue.

**Comment by sah0017** [comment]
@mekealbrown I'm still getting the error ModuleNotFoundError:  No module named 'webdriver_manager'. Your doc doesn't mention putting the location of the chromedriver.exe in the PATH, but I moved the .exe into a folder that was already on the path, and it still isn't finding the module.  Did you have to do anything else so that the code could find it?

**Comment by sah0017** [comment]
@mekealbrown I also tried putting chromedriver in the same directory with the tests, but it still isn't finding it.

**Comment by mekealbrown** [comment]
I will include needing chromedriver in PATH

**Comment by mekealbrown** [comment]
Wiki updated to state that chromedriver needs to be in PATH. Do you want to keep this issue open until a surefire way is found to get these tests running on all machines?

**Comment by mr21Awesomeness** [comment]
Closing Issue, documentation looks good, great job Mekeal!
