### ISSUE TITLE
New Rubric:  As an instructor, I want to be able to add new rubrics to the app.

### ISSUE THREAD

**Issue by sah0017** [Lunatic-Labs/rubricapp#246]
Currently, only a Teamwork rubric is available in the system.  I would like to add additional rubrics to the system.

**Comment by kussmaul** [comment]
Good idea - I coded the OPTIC app so that protocols were defined as JSON, and users could upload their own custom protocols.  Easy to implement, but not an easy way to edit existing protocols in a user-friendly way. Might be good to distinguish between "add rubrics" and "edit/customize rubrics".
