### ISSUE TITLE
Pass 3 tests in test0_signUp_test.py Selenium Test

### ISSUE THREAD

**Issue by mr21Awesomeness** [Lunatic-Labs/rubricapp#254]

**Comment by mr21Awesomeness** [comment]
All three tests pass!

**Comment by mr21Awesomeness** [comment]
Issue Closed!

**Comment by sah0017** [comment]
@mr21Awesomeness Did you have to make any code changes to get the tests to pass, or did they pass right out of the box?

**Comment by mekealbrown** [comment]
I think issue #248 contains the fixes that got test0 passing. It did not work out of the box

**Comment by mekealbrown** [comment]
Apologies, Issue #238

**Comment by mr21Awesomeness** [comment]
There are now 6 new tests in "test0_signUp_test.py" that all pass.
