### ISSUE TITLE
A way to edit a Project to add new students/groups

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#31]
In GitLab by @bmyerz on Oct 3, 2019, 15:57

Questions / suggestions
* Maybe re-upload the students file to make the changes (can detect differences)?
* what do we do about the other tables that use groups/students as foreign keys?

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Oct 3, 2019, 15:58

changed the description

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Oct 3, 2019, 15:59

changed the description

**Comment by sah0017** [comment]
New React page to add students/users.
