### ISSUE TITLE
change url & path for sample files in Create New Project

### ISSUE THREAD

**Issue by kussmaul** [Lunatic-Labs/rubricapp#363]
The "Create new project" dialog has 2 links to sample data files, one of which is:
`https://github.com/sotl-technology/rubricapp/raw/master/sample_file/rosters/sample_roster.xlsx`
which redirects to:
`https://github.com/Lunatic-Labs/rubricapp/raw/master/sample_file/rosters/sample_roster.xlsx`
which displays this error:
`The 'Lunatic-Labs/rubricapp' repository doesn't contain the 'sample_file/rosters/sample_roster.xlsx' path in 'master'. `
A better url might be:
`https://github.com/Lunatic-Labs/rubricapp/blob/master/core/sample_file/rosters/sample_roster.xlsx`

**Comment by maddy020** [comment]
Hey @kussmaul 
I want to work on this issue 
Please let me know in which file I have to make this change

**Comment by kussmaul** [comment]
Hi @maddy020, thanks for your interest. In GitHub (or your IDE) search for `/master/sample_file` and you should find the file(s) and test(s) to edit.

**Comment by maddy020** [comment]
There is no any directory named master 
In branch master and directory core , there is a folder of sample_file but I am unable to find where this needs a change 
Please help me in this @kussmaul

**Comment by kussmaul** [comment]
@maddy020, did you type `/master/sample_file` in the GitHub search bar and select 'in this repository'?

**Comment by maddy020** [comment]
Just solved the issue and created a PR 
Thanks for helping me out @kussmaul

**Comment by kussmaul** [comment]
@maddy020, the same source file, two lines below the line you edited, has another link to `sotl-technology` , which should also be changed.
Ideally, all such urls should be relative (not hard-coded to specific websites) so that each fork is self-contained.
