### ISSUE TITLE
create database with sample/test data - user(s), rubric(s), roster(s), & course(s) 

### ISSUE THREAD

**Issue by kussmaul** [Lunatic-Labs/rubricapp#364]
When rubricapp is run, it has no users, rubrics, or rosters, which makes it hard to get started - I have to create a user, then login, then upload a roster and rubric to create a project. It would be helpful to have some initial data for experimenting.

**Comment by sah0017** [comment]
This can now be accomplished by starting the backend software with the command 'python (or 'python3 from a Mac) setupEnv.py demo'
