### ISSUE TITLE
Add User React

### ISSUE THREAD

**Issue by brianlugo1** [Lunatic-Labs/rubricapp#383]

**Comment by sah0017** [comment]
Changed this to User React since we will Add both students and TA's using the Add User page.

**Comment by brianlugo1** [comment]
As of right now the Add User page is connected to our React App and has supported functionality!!! Functionality of added users persisting to the database!

**Comment by brianlugo1** [comment]
Also the Add User Page displays errors that are handled by corresponding api routes and corresponding model functions!
