### ISSUE TITLE
Create Blank Grading tab in evaluation page

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#47]
In GitLab by @JackyBreak on Oct 17, 2019, 16:27

![image](/uploads/f47dcc5619b67fd98f075605687e86b9/image.png)
By clicking "+blank grade", it yields a new tab with old style.

**Comment by sah0017** [comment]
Closing this issue because we are changing the screen to perform evaluations and storing in a database.
