### ISSUE TITLE
Concurrency: Test when there are multiple graders on the same evaluation

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#50]
In GitLab by @bmyerz on Dec 6, 2019, 11:33

Multiple writes/reads could access the xlsx files concurrently. Can we cause errors when we have multiple users?

**Comment by bmyerz** [comment]
evaluation_commit() is an example from load to save of evaluation file 
This whole code should have a lock around it @bellqueen

**Comment by sah0017** [comment]
No longer using Excel spreadsheets to store data.
