### ISSUE TITLE
Metagroups being numbers gets confused between ints and strings

### ISSUE THREAD

**Issue by bmyerz** [Lunatic-Labs/rubricapp#51]
In GitLab by @bmyerz on Jan 9, 2020, 13:04

If your meta groups are numbers in the students file (e.g., 1,2,3), then the keys are put into the dic_of_choosen dictionary as numbers. But then when the dictionary is accessed with a metaid, there is a key error because the metaid is type string.

This is not a problem when the meta groups are obviously strings (e.g., a,b,c).

To re-create the bug.
1. use this students file [lotsOfGroupsAndMetaGroups.xlsx](/uploads/e00151d0ee6e7e5bf50e57ef9a0a5ab8/lotsOfGroupsAndMetaGroups.xlsx)
2. Create a new evaluation
3. On the evaluations page, try to click on a meta group (1,2, or 3) for the evaluation

**Comment by sah0017** [comment]
Closing this because teams will now have a unique identifier from the database and this shouldn't be an issue any more.
