### ISSUE TITLE
Explore sql strict mode to enforce character length

### ISSUE THREAD

**Issue by bellqueen** [Lunatic-Labs/rubricapp#87]
in issue #80 , we fixed an issue with project names being truncated silently in the database by making the character length in the database and the same length as the html form requirement.

 But to catch similar bugs more quickly in the future, we should also have the database enforce character length. We can do so with 
https://stackoverflow.com/questions/40881773/how-to-turn-on-off-mysql-strict-mode-in-localhost-xampp

**Comment by sah0017** [comment]
No longer relevant
